server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.3:3306/tensquare_friend?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.3:6868/eureka
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: ekko
    ttl: 360000
