server:
  port: 9012
spring:
  application:
    name: tensquare-manager
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
zuul:
  routes:
    tensquare-base:
      path: /label/**
      serviceId: tensquare-base
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user
jwt:
  config:
    key: ekko
    ttl: 360000