server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.16.139:3306/tensquare_qa?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
    instance:
      prefer‐ip‐address: true
feign:    #开启熔断器
  hystrix:
    enabled: true