server:
  port: 9009
spring:
  application:
    name: tensquare_sms
  rabbitmq:
    host: 192.168.1.3
aliyun:
  sms:
    tempCode: SMS_100735040
    signName: 物流系统
    accessKeyId: LTAI0DByuBGlQzS9
    accessKeySecret: OygoBAVQRuCt4vf97Nfwav2NN8gcr2
