server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 134.175.16.139
      port: 27017
      database: spitdb
  redis:
    host: 134.175.16.139
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true