server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.1.3
      port: 27017
      database: spitdb
  redis:
    host: 192.168.1.3
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.3:6868/eureka
  instance:
    prefer-ip-address: true
