server:
  port: 9011
spring:
  application:
    name: tensquare-web
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka #指定eureka注册地址
zuul:
  routes:
    tensquare-base:
      path: /label/**   #拦截路径
      serviceId: tensquare-base  #微服务的名称
    tensquare-qa:
      path: /qa/**
      serviceId: tensquare-qa
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user